/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment;

import javax.swing.JOptionPane;

/**
 *
 * @author Zheliang
 */
public class ResourceBookingGUI extends javax.swing.JFrame {

    /**
     * Creates new form ResourceBookingGUI
     */
    public ResourceBookingGUI() {
        initComponents();
        
        company1 = new Company("HELP Business Group");
        vehicleModel = new VehicleModel(company1.getVehicles());
        bookingModel = new BookingModel();
        vehicleTable.setModel(vehicleModel);
        bookingTable.setModel(bookingModel);
        
        setTitle(company1.getName() + " Car Rental Software");
        setLocationRelativeTo(null);
        // Set Label to Company name 
        nameLabel.setText(company1.getName());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        companyNameLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vehicleTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        addVehicleButton = new javax.swing.JButton();
        deleteVehicleButton = new javax.swing.JButton();
        updateVehicleButton = new javax.swing.JButton();
        displayVehicleInfoButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        bookingTable = new javax.swing.JTable();
        createBookingButton = new javax.swing.JButton();
        deleteBookingButton = new javax.swing.JButton();
        updateBookingButton = new javax.swing.JButton();
        displayDeptBookingButton = new javax.swing.JButton();
        displayBookingInfoButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        activeVehicleLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        openMI = new javax.swing.JMenuItem();
        saveMI = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        closeMI = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        companyNameLabel.setText("Company Name:");

        vehicleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Registration No.", "Vehicle Type", "Make", "Model", "Usage Cost"
            }
        ));
        jScrollPane1.setViewportView(vehicleTable);

        jLabel1.setText("List of Cars");

        addVehicleButton.setText("Add Vehicle");

        deleteVehicleButton.setText("Delete Vehicle");

        updateVehicleButton.setText("Update Vehicle");

        displayVehicleInfoButton.setText("Display Vehicle Information");

        bookingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Booked By", "Date From", "Date To", "No. of Days"
            }
        ));
        jScrollPane2.setViewportView(bookingTable);

        createBookingButton.setText("Create Booking");

        deleteBookingButton.setText("Delete Booking");

        updateBookingButton.setText("Update Booking");

        displayDeptBookingButton.setText("Display Booking By Department");

        displayBookingInfoButton.setText("Display Booking Information");

        jLabel2.setText("Bookings for Vehicle: ");

        activeVehicleLabel.setText("ds");

        jMenu1.setText("File");

        openMI.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openMI.setText("Open");
        jMenu1.add(openMI);

        saveMI.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saveMI.setText("Save");
        jMenu1.add(saveMI);
        jMenu1.add(jSeparator1);

        closeMI.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        closeMI.setText("Exit");
        closeMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeMIActionPerformed(evt);
            }
        });
        jMenu1.add(closeMI);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(deleteBookingButton)
                .addGap(18, 18, 18)
                .addComponent(updateBookingButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addVehicleButton)
                .addGap(18, 18, 18)
                .addComponent(deleteVehicleButton)
                .addGap(18, 18, 18)
                .addComponent(updateVehicleButton)
                .addGap(18, 18, 18)
                .addComponent(createBookingButton)
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(companyNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameLabel))
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(activeVehicleLabel)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(displayVehicleInfoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(displayDeptBookingButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(displayBookingInfoButton)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(companyNameLabel)
                    .addComponent(nameLabel))
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addVehicleButton)
                    .addComponent(deleteVehicleButton)
                    .addComponent(updateVehicleButton)
                    .addComponent(createBookingButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateBookingButton)
                            .addComponent(deleteBookingButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(activeVehicleLabel)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayDeptBookingButton)
                    .addComponent(displayBookingInfoButton)
                    .addComponent(displayVehicleInfoButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeMIActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this, "Really Close?");
        if (result == JOptionPane.OK_OPTION){
            System.exit(0);
        } else if (result == JOptionPane.NO_OPTION){
            JOptionPane.showMessageDialog(this, "Aborted");
        } 
    }//GEN-LAST:event_closeMIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResourceBookingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResourceBookingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResourceBookingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResourceBookingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResourceBookingGUI().setVisible(true);
            }
        });
    }
    
    // Variables Declaration
    private Company company1;
    private VehicleModel vehicleModel;
    private BookingModel bookingModel;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activeVehicleLabel;
    private javax.swing.JButton addVehicleButton;
    private javax.swing.JTable bookingTable;
    private javax.swing.JMenuItem closeMI;
    private javax.swing.JLabel companyNameLabel;
    private javax.swing.JButton createBookingButton;
    private javax.swing.JButton deleteBookingButton;
    private javax.swing.JButton deleteVehicleButton;
    private javax.swing.JButton displayBookingInfoButton;
    private javax.swing.JButton displayDeptBookingButton;
    private javax.swing.JButton displayVehicleInfoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JMenuItem openMI;
    private javax.swing.JMenuItem saveMI;
    private javax.swing.JButton updateBookingButton;
    private javax.swing.JButton updateVehicleButton;
    private javax.swing.JTable vehicleTable;
    // End of variables declaration//GEN-END:variables
}
