/*
 * NAME: TAN ZHELIANG
 * STUDENT ID: B1400653
 * DATE: 06/04/2017
 */
package assignment;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 * GUI Class to handle IO of the program
 * @author Zheliang
 */
public class ResourceBookingGUI extends javax.swing.JFrame {

    /**
     * Creates new form ResourceBookingGUI
     */
    public ResourceBookingGUI() {
        initComponents();
        
        // Initialise variables
        company1 = new Company("HELP Business Group");
        vehicleModel = new VehicleModel(company1.getVehicles());
        blankList = new ArrayList<>();
        bookingModel = new BookingModel(getBlankList());
        avd = new AddVehicleDialog(this, true);
        uvd = new UpdateVehicleDialog(this, true);
        cbd = new CreateBookingDialog(this, true);
        ubd = new UpdateBookingDialog(this, true);
        dvd = new DisplayVehicleDialog(this, true);
        dbd = new DisplayBookingDialog(this, true);
        bbd = new BookingByDeptDialog(this, true);
        
        // Set tables
        vehicleTable.setModel(vehicleModel);
        vehicleTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        bookingTable.setModel(bookingModel);
        bookingTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        // Set JFrame title bar and position
        setTitle(company1.getName() + " Car Rental Software");
        setLocationRelativeTo(null);
        
        // Set JDialog to center on parent
        avd.setLocationRelativeTo(this);
        uvd.setLocationRelativeTo(this);
        cbd.setLocationRelativeTo(this);
        ubd.setLocationRelativeTo(this);
        dvd.setLocationRelativeTo(this);
        dbd.setLocationRelativeTo(this);
        bbd.setLocationRelativeTo(this);
        
        // Set Label to Company name 
        nameLabel.setText(company1.getName());
        
        // Set listener for vehicle table
        vehicleTable.getSelectionModel().addListSelectionListener
        (new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                int rowIndex = vehicleTable.getSelectedRow();
                setSelectedVehicleLabel(rowIndex);
                setBookingModel(rowIndex);
            }
            
            /**
             * Method to set the vehicle label based on selected row index
             * of the vehicle table
             * @param rowIndex 
             */
            public void setSelectedVehicleLabel(int rowIndex) {
                if (rowIndex == -1) {
                    activeVehicleLabel.setText("None");
                } else {
                    Vehicle v1 = vehicleModel.getVehicle(rowIndex);
                    activeVehicleLabel.setText(v1.getRegistrationNumber());
                }
            }
            /**
             * Method to set the booking model based on selected row index
             * of the vehicle table
             * @param rowIndex 
             */
            public void setBookingModel(int rowIndex) {
                if (rowIndex >= 0) {
                    Vehicle v1 = vehicleModel.getVehicle(rowIndex);
                    bookingModel.setBookings(v1.getBookings());
                    bookingModel.updateTable();
                } else {
                    bookingModel.setBookings(getBlankList());
                    bookingModel.updateTable();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fc = new javax.swing.JFileChooser();
        companyNameLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vehicleTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        addVehicleButton = new javax.swing.JButton();
        deleteVehicleButton = new javax.swing.JButton();
        updateVehicleButton = new javax.swing.JButton();
        displayVehicleInfoButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        bookingTable = new javax.swing.JTable();
        createBookingButton = new javax.swing.JButton();
        deleteBookingButton = new javax.swing.JButton();
        updateBookingButton = new javax.swing.JButton();
        displayDeptBookingButton = new javax.swing.JButton();
        displayBookingInfoButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        activeVehicleLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        closeMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        companyNameLabel.setText("Company Name:");

        vehicleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Registration No.", "Vehicle Type", "Make", "Model", "Usage Cost"
            }
        ));
        jScrollPane1.setViewportView(vehicleTable);

        jLabel1.setText("List of Cars");

        addVehicleButton.setText("Add Vehicle");
        addVehicleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVehicleButtonActionPerformed(evt);
            }
        });

        deleteVehicleButton.setText("Delete Vehicle");
        deleteVehicleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteVehicleButtonActionPerformed(evt);
            }
        });

        updateVehicleButton.setText("Update Vehicle");
        updateVehicleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateVehicleButtonActionPerformed(evt);
            }
        });

        displayVehicleInfoButton.setText("Display Vehicle Information");
        displayVehicleInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayVehicleInfoButtonActionPerformed(evt);
            }
        });

        bookingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Booked By", "Date From", "Date To", "No. of Days"
            }
        ));
        jScrollPane2.setViewportView(bookingTable);

        createBookingButton.setText("Create Booking");
        createBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBookingButtonActionPerformed(evt);
            }
        });

        deleteBookingButton.setText("Delete Booking");
        deleteBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBookingButtonActionPerformed(evt);
            }
        });

        updateBookingButton.setText("Update Booking");
        updateBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBookingButtonActionPerformed(evt);
            }
        });

        displayDeptBookingButton.setText("Display Booking By Department");
        displayDeptBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayDeptBookingButtonActionPerformed(evt);
            }
        });

        displayBookingInfoButton.setText("Display Booking Information");
        displayBookingInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBookingInfoButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Selected vehicle: ");

        activeVehicleLabel.setText("None");

        jMenu1.setText("File");

        openMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openMenuItem.setText("Open");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(openMenuItem);

        saveMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saveMenuItem.setText("Save");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(saveMenuItem);
        jMenu1.add(jSeparator1);

        closeMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        closeMenuItem.setText("Exit");
        closeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(closeMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(companyNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameLabel))
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(activeVehicleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 37, Short.MAX_VALUE)
                .addComponent(addVehicleButton)
                .addGap(18, 18, 18)
                .addComponent(deleteVehicleButton)
                .addGap(18, 18, 18)
                .addComponent(updateVehicleButton)
                .addGap(18, 18, 18)
                .addComponent(displayVehicleInfoButton)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(displayBookingInfoButton)
                        .addGap(18, 18, 18)
                        .addComponent(displayDeptBookingButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(createBookingButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteBookingButton)
                        .addGap(18, 18, 18)
                        .addComponent(updateBookingButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(companyNameLabel)
                    .addComponent(nameLabel))
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addVehicleButton)
                    .addComponent(deleteVehicleButton)
                    .addComponent(updateVehicleButton)
                    .addComponent(displayVehicleInfoButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(activeVehicleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteBookingButton)
                    .addComponent(updateBookingButton)
                    .addComponent(createBookingButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayDeptBookingButton)
                    .addComponent(displayBookingInfoButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Method to handle action when close menu item is clicked
     * Closes the program
     * @param evt the event
     */
    private void closeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeMenuItemActionPerformed
    int result = JOptionPane.showConfirmDialog(this, "Really Close?",
            "Warning", JOptionPane.YES_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.OK_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_closeMenuItemActionPerformed
    /**
     * Method to handle action when addVehicle button is clicked
     * Adds a vehicle to the vehicle model
     * @param evt the event
     */
    private void addVehicleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVehicleButtonActionPerformed
        avd.setC1(company1);
        avd.setVisible(true);
        Vehicle v1 = avd.getV1();
        
        if (v1 == null) {
            JOptionPane.showMessageDialog(this, "No Vehicle added.",
                    "Information", JOptionPane.INFORMATION_MESSAGE);
        } else {
            vehicleModel.addVehicle(v1);
            avd.setV1(null);
            JOptionPane.showMessageDialog(this, "Vehicle added.",
                    "Information", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_addVehicleButtonActionPerformed
    /**
     * Method to handle action when deleteButton button is clicked
     * Delete the selected vehicle
     * @param evt the event
     */
    private void deleteVehicleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteVehicleButtonActionPerformed
        int rowSelected = vehicleTable.getSelectedRow();
        if (rowSelected == -1) {
            JOptionPane.showMessageDialog(this, "No vehicle was selected.",
                    "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            if (vehicleModel.getVehicle(rowSelected).getBookings().isEmpty()) {
                vehicleModel.removeVehicle(rowSelected);
            } else {
                int result = JOptionPane.showConfirmDialog(this, "This "
                        + "vehicle has bookings. Delete?", 
                        "Warning", JOptionPane.YES_NO_OPTION, 
                        JOptionPane.WARNING_MESSAGE);
                if (result == JOptionPane.OK_OPTION) {
                    vehicleModel.removeVehicle(rowSelected);
                } else {
                    JOptionPane.showMessageDialog(this, "Vehicle not deleted.", 
                            "Information", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            
        }
    }//GEN-LAST:event_deleteVehicleButtonActionPerformed
    /**
     * Method to handle action when updateVehicle button is clicked
     * Updates the selected vehicle
     * @param evt the event
     */
    private void updateVehicleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateVehicleButtonActionPerformed
        int rowSelected = vehicleTable.getSelectedRow();
        if (rowSelected == -1) {
            JOptionPane.showMessageDialog(this, "No vehicle was selected.",
                    "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            Vehicle v1 = vehicleModel.getVehicle(rowSelected);
            uvd.setC1(company1);
            uvd.setV1(v1);
            uvd.setTextFields();
            uvd.setVisible(true);
            boolean updated = uvd.isUpdated();
            if (updated) {
                vehicleModel.updateTable();
                JOptionPane.showMessageDialog(this, "Vehicle Updated.", 
                        "Information", JOptionPane.INFORMATION_MESSAGE);
                uvd.setUpdated(false);
            } else {
                JOptionPane.showMessageDialog(this, "No Vehicle Updated.", 
                        "Information", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_updateVehicleButtonActionPerformed
    /**
     * Method to handle action when createBooking button is clicked
     * Creates a new booking for selected vehicle
     * @param evt the event
     */
    private void createBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBookingButtonActionPerformed
        int rowSelected = vehicleTable.getSelectedRow();
        if (rowSelected == -1) {
            JOptionPane.showMessageDialog(this, "No vehicle was selected.",
                    "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            Vehicle v1 = vehicleModel.getVehicle(rowSelected);
            cbd.setV1(v1);
            cbd.setVehicleLabel();
            cbd.setVisible(true);
            Booking b1 = cbd.getB1();
            
            if (b1 == null) {
                JOptionPane.showMessageDialog(this, "No Booking Added.",
                        "Information", JOptionPane.INFORMATION_MESSAGE);
            } else {
                bookingModel.addBooking(b1);
                cbd.setB1(null);
                JOptionPane.showMessageDialog(this, "Booking added.", 
                        "Information", JOptionPane.INFORMATION_MESSAGE);
                vehicleModel.updateTable();
                vehicleTable.setRowSelectionInterval(0, rowSelected);
            }
            
        }
    }//GEN-LAST:event_createBookingButtonActionPerformed
    /**
     * Method to handle action when deleteBooking button is clicked
     * Deletes the selected booking
     * @param evt the event
     */
    private void deleteBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBookingButtonActionPerformed
        int vehicleRowSelected = vehicleTable.getSelectedRow();
        int bookingRowSelected = bookingTable.getSelectedRow();
        if (bookingRowSelected == -1) {
            JOptionPane.showMessageDialog(this, "No booking was selected.",
                    "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            bookingModel.removeBooking(bookingRowSelected);
            vehicleModel.updateTable();
            vehicleTable.setRowSelectionInterval(0, vehicleRowSelected);
        }
    }//GEN-LAST:event_deleteBookingButtonActionPerformed
    /**
     * Method to handle action when updateBooking button is clicked
     * Updates the selected booking
     * @param evt the event
     */
    private void updateBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBookingButtonActionPerformed
        int vehicleRowSelected = vehicleTable.getSelectedRow();
        int bookingRowSelected = bookingTable.getSelectedRow();
        
        if (bookingRowSelected == -1 ){
            JOptionPane.showMessageDialog(this, "No booking was selected.",
                    "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            Vehicle v1 = vehicleModel.getVehicle(vehicleRowSelected);
            Booking b1 =  bookingModel.getBooking(bookingRowSelected);
            ubd.setV1(v1);
            ubd.setB1(b1);
            ubd.setVehicleLabel();
            ubd.setTextFields();
            ubd.setVisible(true);
            boolean updated = ubd.isUpdated();
            if (updated) {
                bookingModel.updateTable();
                vehicleModel.updateTable();
                vehicleTable.setRowSelectionInterval(0, vehicleRowSelected);
                JOptionPane.showMessageDialog(this, "Booking updated");
                ubd.setUpdated(false);
            } else {
                JOptionPane.showMessageDialog(this, "No booking updated");
            }
            
        }
    }//GEN-LAST:event_updateBookingButtonActionPerformed
    /**
     * Method to handle action when displayVehicleInfo button is clicked
     * Displays a window to display all vehicle information
     * @param evt the event
     */
    private void displayVehicleInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayVehicleInfoButtonActionPerformed
        if (!vehicleModel.getVehicles().isEmpty()) {
            dvd.setC1(company1);
            dvd.setVehicleInfoTextArea();
            dvd.setVisible(true);
            
        } else {
            JOptionPane.showMessageDialog(this, "There are no vehicles in the "
                    + "system.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_displayVehicleInfoButtonActionPerformed
    /**
     * Method to handle action when displayBookingInfo button is clicked
     * Displays a window to display all booking info for the selected vehicle
     * @param evt the event
     */
    private void displayBookingInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBookingInfoButtonActionPerformed
        int rowSelected = vehicleTable.getSelectedRow();
        if (rowSelected == -1) {
            JOptionPane.showMessageDialog(this, "No vehicle was selected.",
                    "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            Vehicle v1 = vehicleModel.getVehicle(rowSelected);
            if (!v1.getBookings().isEmpty()) {
                dbd.setV1(v1);
                dbd.setVehicleLabel();
                dbd.setBookingTextArea();
                dbd.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "There are no bookings "
                        + "made for the vehicle.", "Information", 
                        JOptionPane.INFORMATION_MESSAGE);
            }

        }
    }//GEN-LAST:event_displayBookingInfoButtonActionPerformed
    /**
     * Method to handle action when displayDeptBooking button is clicked
     * Displays a window to display booking info based on department 
     * @param evt the event
     */
    private void displayDeptBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayDeptBookingButtonActionPerformed
        if (vehicleModel.getVehicles().isEmpty()) {
            JOptionPane.showMessageDialog(this, "There are no vehicles in "
                    + "the system.", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            bbd.setC1(company1);
            bbd.setVisible(true);
        }
    }//GEN-LAST:event_displayDeptBookingButtonActionPerformed
    /**
     * Method to handle action when save menu item is clicked
     * Saves all objects into a file on to the computer
     * @param evt the event
     */
    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        int result = fc.showSaveDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION) {
            File newFile = fc.getSelectedFile();
            String fileName = newFile.toString();
            FileOutputStream fos = null;
            ObjectOutputStream oos = null;
            try {
                fos = new FileOutputStream(fileName);
                oos = new ObjectOutputStream(fos);
                oos.writeObject(company1);
                oos.flush();
                oos.close();
            } catch (IOException ioe) {
                JOptionPane.showMessageDialog(this, ioe.getMessage(), 
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        } 
    }//GEN-LAST:event_saveMenuItemActionPerformed
    /**
     * Method to handle action when open menu item is clicked
     * Reads a file to retrieve all objects and stores in the program
     * @param evt the event
     */
    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        int result = fc.showOpenDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION) {
            File openFile = fc.getSelectedFile();
            String fileName = openFile.toString();
            FileInputStream fis = null;
            ObjectInputStream ois = null;
            try {
                fis = new FileInputStream(fileName);
                ois = new ObjectInputStream(fis);
                
                company1 = (Company) ois.readObject();
                vehicleModel.setVehicles(company1.getVehicles());
                vehicleTable.setModel(vehicleModel);
                vehicleModel.updateTable();
                ois.close();
            } catch (FileNotFoundException fnfe) {
                JOptionPane.showMessageDialog(this, fnfe.getMessage(), 
                        "Error", JOptionPane.ERROR_MESSAGE);
            } catch (ClassNotFoundException cnfe ) {
                JOptionPane.showMessageDialog(this, cnfe.getMessage(), 
                        "Error", JOptionPane.ERROR_MESSAGE);
            } catch (IOException ioe) {
                JOptionPane.showMessageDialog(this, ioe.getMessage(), 
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_openMenuItemActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResourceBookingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResourceBookingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResourceBookingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResourceBookingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResourceBookingGUI().setVisible(true);
            }
        });
    }
    
    // Variables Declaration
    /**
     * Variable to store the company
     */
    private Company company1;
    /**
     * Variable to store the vehicle table model
     */
    private VehicleModel vehicleModel;
    /**
     * Variable to store a blank collection of booking
     */
    private ArrayList<Booking> blankList;
    /**
     * Variable to store the booking table model
     */
    private BookingModel bookingModel;
    /**
     * Variable to store the add vehicle dialog
     */
    private AddVehicleDialog avd;
    /**
     * Variable to store the update vehicle dialog
     */
    private UpdateVehicleDialog uvd;
    /**
     * Variable to store the create booking dialog
     */
    private CreateBookingDialog cbd;
    /**
     * Variable to store the update booking dialog
     */
    private UpdateBookingDialog ubd;
    /**
     * Variable to store the display vehicle dialog
     */
    private DisplayVehicleDialog dvd;
    /**
     * Variable to store the display booking dialog
     */
    private DisplayBookingDialog dbd;
    /**
     * Variable to store the booking by dept dialog
     */
    private BookingByDeptDialog bbd;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activeVehicleLabel;
    private javax.swing.JButton addVehicleButton;
    private javax.swing.JTable bookingTable;
    private javax.swing.JMenuItem closeMenuItem;
    private javax.swing.JLabel companyNameLabel;
    private javax.swing.JButton createBookingButton;
    private javax.swing.JButton deleteBookingButton;
    private javax.swing.JButton deleteVehicleButton;
    private javax.swing.JButton displayBookingInfoButton;
    private javax.swing.JButton displayDeptBookingButton;
    private javax.swing.JButton displayVehicleInfoButton;
    private javax.swing.JFileChooser fc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JButton updateBookingButton;
    private javax.swing.JButton updateVehicleButton;
    private javax.swing.JTable vehicleTable;
    // End of variables declaration//GEN-END:variables

    /**
     * Method to retrieve the blank arraylist
     * @return the blankList 
     */
    public ArrayList<Booking> getBlankList() {
        return blankList;
    }
}
