/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Zheliang
 */
public class ResourceBookingGUI extends javax.swing.JFrame {

    /**
     * Creates new form ResourceBookingGUI
     */
    public ResourceBookingGUI() {
        initComponents();
        
        company1 = new Company("HELP Business Group");
        vehicleModel = new VehicleModel(company1.getVehicles());
        blankList = new ArrayList<>();
        bookingModel = new BookingModel(getBlankList());
        avd = new AddVehicleDialog(this, true);
        uvd = new UpdateVehicleDialog(this, true);
        cbd = new CreateBookingDialog(this, true);
        ubd = new UpdateBookingDialog(this, true);
        
        vehicleTable.setModel(vehicleModel);
        vehicleTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        bookingTable.setModel(bookingModel);
        bookingTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        avd.setCompany1(company1);
        uvd.setCompany1(company1);
        
        setTitle(company1.getName() + " Car Rental Software");
        setLocationRelativeTo(null);
        // Set Label to Company name 
        nameLabel.setText(company1.getName());
        
        vehicleTable.getSelectionModel().addListSelectionListener
        (new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                int rowIndex = vehicleTable.getSelectedRow();
                setSelectedVehicleLabel(rowIndex);
                setBookingModel(rowIndex);
            }
            
            public void setSelectedVehicleLabel(int rowIndex) {
                if (rowIndex == -1) {
                    activeVehicleLabel.setText("None");
                } else {
                    Vehicle v1 = vehicleModel.getVehicles().get(rowIndex);
                    activeVehicleLabel.setText(v1.getRegistrationNumber());
                }
            }
            
            public void setBookingModel(int rowIndex) {
                if (rowIndex >= 0) {
                    Vehicle v1 = vehicleModel.getVehicles().get(rowIndex);
                    bookingModel.setBookings(v1.getBookings());
                    bookingModel.updateTable();
                } else {
                    bookingModel.setBookings(getBlankList());
                    bookingModel.updateTable();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        companyNameLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vehicleTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        addVehicleButton = new javax.swing.JButton();
        deleteVehicleButton = new javax.swing.JButton();
        updateVehicleButton = new javax.swing.JButton();
        displayVehicleInfoButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        bookingTable = new javax.swing.JTable();
        createBookingButton = new javax.swing.JButton();
        deleteBookingButton = new javax.swing.JButton();
        updateBookingButton = new javax.swing.JButton();
        displayDeptBookingButton = new javax.swing.JButton();
        displayBookingInfoButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        activeVehicleLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        closeMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        companyNameLabel.setText("Company Name:");

        vehicleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Registration No.", "Vehicle Type", "Make", "Model", "Usage Cost"
            }
        ));
        jScrollPane1.setViewportView(vehicleTable);

        jLabel1.setText("List of Cars");

        addVehicleButton.setText("Add Vehicle");
        addVehicleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVehicleButtonActionPerformed(evt);
            }
        });

        deleteVehicleButton.setText("Delete Vehicle");
        deleteVehicleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteVehicleButtonActionPerformed(evt);
            }
        });

        updateVehicleButton.setText("Update Vehicle");
        updateVehicleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateVehicleButtonActionPerformed(evt);
            }
        });

        displayVehicleInfoButton.setText("Display Vehicle Information");

        bookingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Booked By", "Date From", "Date To", "No. of Days"
            }
        ));
        jScrollPane2.setViewportView(bookingTable);

        createBookingButton.setText("Create Booking");
        createBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBookingButtonActionPerformed(evt);
            }
        });

        deleteBookingButton.setText("Delete Booking");
        deleteBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBookingButtonActionPerformed(evt);
            }
        });

        updateBookingButton.setText("Update Booking");
        updateBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBookingButtonActionPerformed(evt);
            }
        });

        displayDeptBookingButton.setText("Display Booking By Department");

        displayBookingInfoButton.setText("Display Booking Information");

        jLabel2.setText("Selected vehicle: ");

        activeVehicleLabel.setText("None");

        jMenu1.setText("File");

        openMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openMenuItem.setText("Open");
        jMenu1.add(openMenuItem);

        saveMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saveMenuItem.setText("Save");
        jMenu1.add(saveMenuItem);
        jMenu1.add(jSeparator1);

        closeMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        closeMenuItem.setText("Exit");
        closeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(closeMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(companyNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameLabel))
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(activeVehicleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(displayVehicleInfoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayBookingInfoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayDeptBookingButton)
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addVehicleButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteVehicleButton)
                        .addGap(18, 18, 18)
                        .addComponent(updateVehicleButton)
                        .addGap(18, 18, 18)
                        .addComponent(createBookingButton)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(deleteBookingButton)
                        .addGap(18, 18, 18)
                        .addComponent(updateBookingButton)
                        .addGap(170, 170, 170))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(companyNameLabel)
                    .addComponent(nameLabel))
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addVehicleButton)
                    .addComponent(deleteVehicleButton)
                    .addComponent(updateVehicleButton)
                    .addComponent(createBookingButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(activeVehicleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteBookingButton)
                    .addComponent(updateBookingButton))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayDeptBookingButton)
                    .addComponent(displayBookingInfoButton)
                    .addComponent(displayVehicleInfoButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeMenuItemActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this, "Really Close?");
        if (result == JOptionPane.OK_OPTION){
            System.exit(0);
        } else if (result == JOptionPane.NO_OPTION){
            JOptionPane.showMessageDialog(this, "Aborted");
        } 
    }//GEN-LAST:event_closeMenuItemActionPerformed

    private void addVehicleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVehicleButtonActionPerformed
        avd.setLocationRelativeTo(this);
        avd.setVisible(true);
        Vehicle v1 = avd.getV1();
        
        if (v1 == null) {
            JOptionPane.showMessageDialog(this, "Cancelled");
        } else {
            vehicleModel.addVehicle(v1);
            avd.setV1(null);
        }
    }//GEN-LAST:event_addVehicleButtonActionPerformed

    private void deleteVehicleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteVehicleButtonActionPerformed
        int rowSelected = vehicleTable.getSelectedRow();
        if (rowSelected == -1) {
            JOptionPane.showMessageDialog(this, "No vehicle was selected.",
                    "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            vehicleModel.removeVehicle(rowSelected);
        }
    }//GEN-LAST:event_deleteVehicleButtonActionPerformed

    private void updateVehicleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateVehicleButtonActionPerformed
        int rowSelected = vehicleTable.getSelectedRow();
        if (rowSelected == -1) {
            JOptionPane.showMessageDialog(this, "No vehicle was selected.",
                    "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            Vehicle v1 = vehicleModel.getVehicles().get(rowSelected);
            uvd.setLocationRelativeTo(null);
            uvd.setV1(v1);
            uvd.setTextFields(v1.getRegistrationNumber(), v1.getMake(), 
                    v1.getModel());
            uvd.setVisible(true);
            boolean updated = uvd.isUpdated();
            if (updated) {
                vehicleModel.updateTable();
                JOptionPane.showMessageDialog(this, "Vehicle Updated");
                uvd.setUpdated(false);
            } else {
                JOptionPane.showMessageDialog(this, "No Vehicle Updated");
            }
        }
    }//GEN-LAST:event_updateVehicleButtonActionPerformed

    private void createBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBookingButtonActionPerformed
        int rowSelected = vehicleTable.getSelectedRow();
        if (rowSelected == -1) {
            JOptionPane.showMessageDialog(this, "No vehicle was selected.",
                    "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            Vehicle v1 = vehicleModel.getVehicles().get(rowSelected);
            cbd.setV1(v1);
            cbd.setLocationRelativeTo(this);
            cbd.setVehicleLabel(v1);
            cbd.setVisible(true);
            Booking b1 = cbd.getB1();
            
            if (b1 == null) {
                JOptionPane.showMessageDialog(this, "Cancelled");
            } else {
                bookingModel.addBooking(b1);
                cbd.setB1(null);
                vehicleModel.updateTable();
            }
            
        }
    }//GEN-LAST:event_createBookingButtonActionPerformed

    private void deleteBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBookingButtonActionPerformed
        int rowSelected = bookingTable.getSelectedRow();
        if (rowSelected == -1) {
            JOptionPane.showMessageDialog(this, "No booking was selected.",
                    "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            bookingModel.removeBooking(rowSelected);
        }
    }//GEN-LAST:event_deleteBookingButtonActionPerformed

    private void updateBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBookingButtonActionPerformed
        int rowSelected = bookingTable.getSelectedRow();
        
        if (rowSelected == -1 ){
            JOptionPane.showMessageDialog(this, "No booking was selected.",
                    "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            Vehicle v1 = vehicleModel.getVehicles().get(rowSelected);
            Booking b1 =  bookingModel.getBookings().get(rowSelected);
            ubd.setV1(v1);
            ubd.setB1(b1);
            ubd.setLocationRelativeTo(this);
            ubd.setVisible(true);
            
        }
    }//GEN-LAST:event_updateBookingButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResourceBookingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResourceBookingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResourceBookingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResourceBookingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResourceBookingGUI().setVisible(true);
            }
        });
    }
    
    // Variables Declaration
    private Company company1;
    private VehicleModel vehicleModel;
    private ArrayList<Booking> blankList;
    private BookingModel bookingModel;
    private AddVehicleDialog avd;
    private UpdateVehicleDialog uvd;
    private CreateBookingDialog cbd;
    private UpdateBookingDialog ubd;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activeVehicleLabel;
    private javax.swing.JButton addVehicleButton;
    private javax.swing.JTable bookingTable;
    private javax.swing.JMenuItem closeMenuItem;
    private javax.swing.JLabel companyNameLabel;
    private javax.swing.JButton createBookingButton;
    private javax.swing.JButton deleteBookingButton;
    private javax.swing.JButton deleteVehicleButton;
    private javax.swing.JButton displayBookingInfoButton;
    private javax.swing.JButton displayDeptBookingButton;
    private javax.swing.JButton displayVehicleInfoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JButton updateBookingButton;
    private javax.swing.JButton updateVehicleButton;
    private javax.swing.JTable vehicleTable;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the blankList
     */
    public ArrayList<Booking> getBlankList() {
        return blankList;
    }
}
